### ISSUE TITLE
Polygon Icon in Desktop Version

### ISSUE THREAD

**Issue by felixfinkbeiner** [Plant-for-the-Planet-org/planet-webapp#1130] opened 2021-06-20 14:47 UTC
Please display the polygon icon we use in the mobile version of the site, just left of the site name in the web version

<img width="258" alt="Screenshot 2021-06-20 at 10 44 01" src="https://user-images.githubusercontent.com/29404196/122678357-d15abc80-d1e6-11eb-8f37-6d39145106c1.png">

**Comment by norbertschuler** [comment] 2021-06-20 17:53
Can you explain that in more detail. I am afraid I don't get the idea behind your request. 

Currently the mobile (small Screen) version first shows as following 
![image](https://user-images.githubusercontent.com/1532418/122683685-1b509c00-d201-11eb-9e3d-fb95c6e72660.jpeg)

And if you click the polygon icon the display changes to this:
![image](https://user-images.githubusercontent.com/1532418/122683700-36231080-d201-11eb-9a77-bd0d7d9b44a6.jpeg)

**Comment by felixfinkbeiner** [comment] 2021-07-04 12:16
Not sure if this is solved already. Essentially, nothing changes about the mobile version. But in the desktop version, we show the icon next to the site name. At the moment, we do not use the icon in the desktop version

**Comment by norbertschuler** [comment] 2021-07-04 13:05
@felixfinkbeiner as you see the linked pull request https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1133 with changes programmed for this issue is not yet merged, so the issue is not yet resolved for the production website. But you can test it with the test version linked in the pull request.

**Closed** 2021-07-19 12:58 UTC
Labels: enhancement
